"""Deleted choice_id foreign key from statistics table..

Revision ID: 5270b7f05da6
Revises: 0e88b4f61f77
Create Date: 2023-01-13 06:59:07.863624

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5270b7f05da6'
down_revision = '0e88b4f61f77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=postgresql.UUID(),
               nullable=False)

    with op.batch_alter_table('statistics', schema=None) as batch_op:
        batch_op.drop_constraint('statistics_choice_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statistics', schema=None) as batch_op:
        batch_op.create_foreign_key('statistics_choice_id_fkey', 'classes', ['choice_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=postgresql.UUID(),
               nullable=True)

    # ### end Alembic commands ###
