version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 5000:5000
    depends_on:
      - database
    links:
      - database
    environment:
      POSTGRES_HOST: database
    entrypoint: /app/entrypoint.sh

  database:
    image: postgres:13-alpine
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432

volumes:
  postgres-data: